name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        sudo apt install python2 g++ make -y
        sudo apt install yarn -y
        
    - name: Print current directory and yarn install
      run: |
        sudo apt remove cmdtest
        sudo apt remove yarn
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
        sudo apt-get update
        sudo apt-get install yarn -y
        yarn install

    - name: Docker Build & Push Action
      uses: mr-smithers-excellent/docker-build-push@v6.3
      with:
        image: jubuitrago/jubuitrago
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


  #deploy:
   # runs-on: ubuntu-latest
    #needs: build
    #steps:
   #- name: Deploy app
   #   run: |
   #     ssh user@server

            
    
    
